# Generated by Django 4.2.2 on 2023-06-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunoId', models.IntegerField()),
                ('professorId', models.IntegerField()),
                ('TurmaId', models.IntegerField()),
            ],
        ),
    ]
